In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split,GridSearchCV,StratifiedKFold
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder,LabelEncoder
from sklearn.metrics import(
    accuracy_score,precision_score,recall_score,f1_score,roc_auc_score,classification_report,confusion_matrix,roc_curve
)
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
import warnings
warnings.filterwarnings('ignore')

In [3]:
df=pd.read_csv('banking_loan_default_dataset_500_rows.csv')

In [4]:
df.head()

,customer_id,age,income_monthly,loan_amount,credit_score,employment_years,debt_to_income,existing_loans,dependents,bank_balance,interest_rate,employment_status,marital_status,education,loan_purpose,city_tier,previous_defaults,loan_default
0,CUST1362,29,143036.0,200322,574.0,4.7,0.22,5,4,301629,13.12,Business,Married,Graduate,Home,Tier 3,0,No
1,CUST1074,28,56102.0,863738,810.0,2.8,0.13,5,3,620324,8.92,Salaried,Married,Undergraduate,Home,Tier 2,0,Yes
2,CUST1375,40,93703.0,428165,687.0,8.3,0.51,3,2,94037,10.44,Business,Divorced,Undergraduate,Education,Tier 3,0,Yes
3,CUST1156,52,123787.0,364997,651.0,0.6,0.17,0,0,483454,8.08,Self-employed,Married,Postgraduate,Education,Tier 3,1,Yes
4,CUST1105,25,48355.0,855688,662.0,3.6,0.47,3,0,906311,8.91,Salaried,Married,Undergraduate,Education,Tier 1,0,Yes

In [5]:
df.shape

(500, 18)

In [6]:
df.info

<bound method DataFrame.info of     customer_id  age  income_monthly  loan_amount  credit_score  \
0      CUST1362   29        143036.0       200322         574.0
1      CUST1074   28         56102.0       863738         810.0
2      CUST1375   40         93703.0       428165         687.0
3      CUST1156   52        123787.0       364997         651.0
4      CUST1105   25         48355.0       855688         662.0
..          ...  ...             ...          ...           ...
495    CUST1107   59        174542.0       150158         636.0
496    CUST1271   23        122573.0       677433         557.0
497    CUST1349   60         19062.0       502268           NaN
498    CUST1436   49        134748.0       201563         664.0
499    CUST1103   55             NaN       698373         717.0

     employment_years  debt_to_income  existing_loans  dependents  \
0                 4.7            0.22               5           4
1                 2.8            0.13               5           3
2                 8.3            0.51               3           2
3                 0.6            0.17               0           0
4                 3.6            0.47               3           0
..                ...             ...             ...         ...
495               0.7            0.19               0           4
496               7.9            0.55               3           3
497               2.2            0.45               2           5
498               0.8            0.38               5           4
499               1.5            0.32               2           0

     bank_balance  interest_rate employment_status marital_status  \
0          301629          13.12          Business        Married
1          620324           8.92          Salaried        Married
2           94037          10.44          Business       Divorced
3          483454           8.08     Self-employed        Married
4          906311           8.91          Salaried        Married
..            ...            ...               ...            ...
495        968676          14.49          Salaried       Divorced
496         17100           9.20          Business        Married
497        886864          14.65          Business         Single
498         83116          11.22     Self-employed        Married
499        853231          12.34          Salaried        Married

         education loan_purpose city_tier  previous_defaults loan_default
0         Graduate         Home    Tier 3                  0           No
1    Undergraduate         Home    Tier 2                  0          Yes
2    Undergraduate    Education    Tier 3                  0          Yes
3     Postgraduate    Education    Tier 3                  1          Yes
4    Undergraduate    Education    Tier 1                  0          Yes
..             ...          ...       ...                ...          ...
495       Graduate         Home    Tier 2                  0           No
496  Undergraduate     Personal    Tier 1                  0          Yes
497       Graduate    Education    Tier 3                  0          Yes
498  Undergraduate         Home    Tier 1                  1          Yes
499    High School      Vehicle    Tier 2                  0           No

[500 rows x 18 columns]>

In [7]:
df.isnull().sum().sort_values(ascending=False).head(15)

credit_score         15
income_monthly       15
education            15
debt_to_income       15
employment_years     15
customer_id           0
age                   0
loan_amount           0
dependents            0
existing_loans        0
bank_balance          0
interest_rate         0
employment_status     0
marital_status        0
loan_purpose          0
dtype: int64

In [8]:
target_column='loan_default'
df=df.dropna(subset=[target_column]).copy()

X=df.drop(columns=[target_column])
y=df[target_column]

print('Target Values : ')
print(y.value_counts())

Target Values :
loan_default
Yes    357
No     143
Name: count, dtype: int64

In [9]:
label_encoder=LabelEncoder()
y=label_encoder.fit_transform(y.astype(str))

print('Classes : ',list(label_encoder.classes_))
print('Encoded classes : ',np.unique(y))

Classes :  ['No', 'Yes']
Encoded classes :  [0 1]

In [10]:
numeric_features=X.select_dtypes(include=np.number).columns.tolist()
categorical_features=X.select_dtypes(exclude=np.number).columns.tolist()
print('Numeric features : ',numeric_features)
print('\nCategorical features : ',categorical_features)

Numeric features :  ['age', 'income_monthly', 'loan_amount', 'credit_score', 'employment_years', 'debt_to_income', 'existing_loans', 'dependents', 'bank_balance', 'interest_rate', 'previous_defaults']

Categorical features :  ['customer_id', 'employment_status', 'marital_status', 'education', 'loan_purpose', 'city_tier']

In [11]:
X_train,X_test,y_train,y_test=train_test_split(
    X,y,
    test_size=0.20,random_state=42,
    stratify=y
)
print('Training data : ',X_train.shape)
print('Testing data : ',X_test.shape)

Training data :  (400, 17)
Testing data :  (100, 17)

In [13]:
numeric_transformer=Pipeline([
    ('imputer',SimpleImputer(strategy='median'))
])
categorical_transformer=Pipeline([
    ('imputer',SimpleImputer(strategy='most_frequent')),
    ('onehot',OneHotEncoder(handle_unknown='ignore'))
])
preprocessor=ColumnTransformer([
    ('num',numeric_transformer,numeric_features),
    ('cat',categorical_transformer,categorical_features)
])

In [15]:
xgb_model=XGBClassifier(
    n_estimators=200,
    learning_rate=0.05,
    max_depth=4,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    eval_metric='logloss'
)
xgb_pipeline=Pipeline([
    ('preprocessor',preprocessor),
    ('model',xgb_model)
])
xgb_pipeline.fit(X_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median'))]),
                                                  ['age', 'income_monthly',
                                                   'loan_amount',
                                                   'credit_score',
                                                   'employment_years',
                                                   'debt_to_income',
                                                   'existing_loans',
                                                   'dependents', 'bank_balance',
                                                   'interest_rate',
                                                   'previous_defaults']),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImpu...
                               feature_types=None, feature_weights=None,
                               gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=0.05,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=4, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=200, n_jobs=None,
                               num_parallel_tree=None, ...))])

In [16]:
lgb_model=LGBMClassifier(
    n_estimators=200,
    learning_rate=0.05,
    max_depth=-1,
    num_leaves=31,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    verbosity=-1
)
lgb_pipeline=Pipeline([
    ('preprecessor',preprocessor),
    ('model',lgb_model)
])

lgb_pipeline.fit(X_train,y_train)

Pipeline(steps=[('preprecessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median'))]),
                                                  ['age', 'income_monthly',
                                                   'loan_amount',
                                                   'credit_score',
                                                   'employment_years',
                                                   'debt_to_income',
                                                   'existing_loans',
                                                   'dependents', 'bank_balance',
                                                   'interest_rate',
                                                   'previous_defaults']),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['customer_id',
                                                   'employment_status',
                                                   'marital_status',
                                                   'education', 'loan_purpose',
                                                   'city_tier'])])),
                ('model',
                 LGBMClassifier(colsample_bytree=0.8, learning_rate=0.05,
                                n_estimators=200, random_state=42,
                                subsample=0.8, verbosity=-1))])

In [22]:
xgb_pred=xgb_pipeline.predict(X_test)
xgb_prob=xgb_pipeline.predict_proba(X_test)[:,1]

lgb_pred=lgb_pipeline.predict(X_test)
lgb_prob=lgb_pipeline.predict_proba(X_test)[:,1]

def get_metrics(y_true,y_pred,y_prob):
    return{
        'Accuracy': accuracy_score(y_true,y_pred),
        'Precision': precision_score(y_true,y_pred,zero_division=0),
        'Recall':recall_score(y_true,y_pred,zero_division=0),
        'f1_score':f1_score(y_true,y_pred,zero_division=0),
        'ROC-AUC': roc_auc_score(y_true,y_prob)
    }
results=pd.DataFrame([
    get_metrics(y_test,xgb_pred,xgb_prob),
    get_metrics(y_test,lgb_pred,lgb_prob)
],index=['XGBoost','LightGBM'])

results.round(4)

          Accuracy  Precision  Recall  f1_score  ROC-AUC
XGBoost       0.72     0.7471  0.9155    0.8228   0.7115
LightGBM      0.69     0.7439  0.8592    0.7974   0.7067